### ISSUE TITLE
Can't change the default font size without changing the font itself

### ISSUE THREAD

**Issue by tvasenin** [YomikoR/VapourSynth-Editor#47]
Win10 x64, latest portable QT6 build.

I try to decrease the size of the default font (Monotype), but when trying to change font properties, the font is set to Sergoe UI and there's no Monotype font in the list.

**Comment by YomikoR** [comment]
In order not to assume the existence of any specific font, the default behavior of the editor is to request Windows for its default monospaced font (just like a webpage asking for a serif font). The chosen font is possibly Courier New, but can be overriden by OS settings. Unfortunately, I cannot tell the result of the font request within Qt framework.
Since you are already there for customization, just pick your favorites and save.

**Comment by tvasenin** [comment]
Ok, I now see the logic behind this, and agree there's nothing to fix here, thanks!
