### ISSUE TITLE
[Re-Quest] for audio support 

### ISSUE THREAD

**Issue by sosie-js** [YomikoR/VapourSynth-Editor#57]
Hi YomikoR

 どうもありがとう!

I know this is[ old issue request](https://github.com/YomikoR/VapourSynth-Editor/issues/11) but I have succeeded to have the sound in [vspreview](https://github.com/Jaded-Encoding-Thaumaturgy/vs-preview) - maybe some code can be borrowed from there and since VS api4  -, we have a best candidate than outdated bestaudiosource to get audio support: Mr [bestsource](https://github.com/vapoursynth/bestsource). If we dig a bit , then we can converge to a [ vapoursynth script](https://gist.github.com/sosie-js/3384fc640a1d1d4c2cd00c0ac791d5ed#file-vs4-audio-test-vpy) that mux audio and video and allow to Trim... 

 Is there many chance to have audio support then in your nice and clean interface ?

**Comment by YomikoR** [comment]
There's already a cheap implementation of audio playback in Windows releases using Qt built-in features. Through Qt I can only tell the backend to start and stop playback, but never acquire the actual timestamps each frame is played, so functionality is limited to the playback of a single track, as a standalone VS output node, and with a 3-frame delay because some buffer is needed by the backend. Seeking is muted for the same reason.

If you want to try the audio playback on other platforms, you might patch all the `#ifdef Q_OS_WIN // AUDIO` macros before building.

**Comment by sosie-js** [comment]
Ok thanks for your response.
